const express = require('express');
const router = express.Router();
const guestRouter = require('./guest.router');
const userRouter = require('./user.router');
const typeRouter = require('./type.router');
const sportFieldRouter = require('./sportField.router');
const categoryPolicyRouter = require('./categoryPolicy.router');
const policyRouter = require('./policy.router');
const equipmentRouter = require('./equipment.router');
const consumableRouter = require('./consumable.router');
const bookingRouter = require('./booking.router');
const matchmakingRouter = require('./matchmaking.router');
const maintenanceRouter = require('./maintenance.router');
const scheduleRouter = require('./schedule.router');
const consumablePurchaseRouter = require('./consumablePurchase.router');
const equipmentRentalRouter = require('./equipmentRental.router');
const paymentRouter = require('./payment.router');
const walletRouter = require('./wallet.router');
const fakeRouter = require('./fake.router');
const newsRouter = require('./news.router');


router.use('/news', newsRouter);
router.use('/guest', guestRouter);
router.use('/user', userRouter);
router.use('/type', typeRouter);
router.use('/sport-field', sportFieldRouter);
router.use('/category-policy', categoryPolicyRouter);
router.use('/policy', policyRouter);
router.use('/equipment', equipmentRouter);
router.use('/consumable', consumableRouter);
router.use('/booking', bookingRouter);
router.use('/matchmaking', matchmakingRouter);
router.use('/maintenance', maintenanceRouter);
router.use('/schedule', scheduleRouter);
router.use('/consumable-purchase', consumablePurchaseRouter);
router.use('/equipment-rental', equipmentRentalRouter);
router.use('/payment', paymentRouter);
router.use('/wallet', walletRouter);
router.use('/fake', fakeRouter);

module.exports = router;
